namespace WildernessCallouts.Types
{
    using Rage;
    using Rage.Native;

    internal static class Scenario
    {
        public const string WORLD_HUMAN_AA_COFFEE = "WORLD_HUMAN_AA_COFFEE";
        public const string WORLD_HUMAN_AA_SMOKE = "WORLD_HUMAN_AA_SMOKE";
        //public const string WORLD_HUMAN_BINOCULARS = "WORLD_HUMAN_BINOCULARS";
        //public const string WORLD_HUMAN_BUM_FREEWAY = "WORLD_HUMAN_BUM_FREEWAY";
        //public const string WORLD_HUMAN_BUM_SLUMPED = "WORLD_HUMAN_BUM_SLUMPED";
        //public const string WORLD_HUMAN_BUM_STANDING = "WORLD_HUMAN_BUM_STANDING";
        //public const string WORLD_HUMAN_BUM_WASH = "WORLD_HUMAN_BUM_WASH";
        //public const string WORLD_HUMAN_CAR_PARK_ATTENDANT = "WORLD_HUMAN_CAR_PARK_ATTENDANT";
        //public const string WORLD_HUMAN_CHEERING = "WORLD_HUMAN_CHEERING";
        public const string WORLD_HUMAN_CLIPBOARD = "WORLD_HUMAN_CLIPBOARD";
        //public const string WORLD_HUMAN_CONST_DRILL = "WORLD_HUMAN_CONST_DRILL";
        //public const string WORLD_HUMAN_COP_IDLES = "WORLD_HUMAN_COP_IDLES";
        //public const string WORLD_HUMAN_DRINKING = "WORLD_HUMAN_DRINKING";
        //public const string WORLD_HUMAN_DRUG_DEALER = "WORLD_HUMAN_DRUG_DEALER";
        //public const string WORLD_HUMAN_DRUG_DEALER_HARD = "WORLD_HUMAN_DRUG_DEALER_HARD";
        //public const string WORLD_HUMAN_MOBILE_FILM_SHOCKING = "WORLD_HUMAN_MOBILE_FILM_SHOCKING";
        //public const string WORLD_HUMAN_GARDENER_LEAF_BLOWER = "WORLD_HUMAN_GARDENER_LEAF_BLOWER";
        //public const string WORLD_HUMAN_GARDENER_PLANT = "WORLD_HUMAN_GARDENER_PLANT";
        //public const string WORLD_HUMAN_GOLF_PLAYER = "WORLD_HUMAN_GOLF_PLAYER";
        //public const string WORLD_HUMAN_GUARD_PATROL = "WORLD_HUMAN_GUARD_PATROL";
        //public const string WORLD_HUMAN_GUARD_STAND = "WORLD_HUMAN_GUARD_STAND";
        //public const string WORLD_HUMAN_GUARD_STAND_ARMY = "WORLD_HUMAN_GUARD_STAND_ARMY";
        //public const string WORLD_HUMAN_HAMMERING = "WORLD_HUMAN_HAMMERING";
        //public const string WORLD_HUMAN_HANG_OUT_STREET = "WORLD_HUMAN_HANG_OUT_STREET";
        //public const string WORLD_HUMAN_HIKER_STANDING = "WORLD_HUMAN_HIKER_STANDING";
        //public const string WORLD_HUMAN_HUMAN_STATUE = "WORLD_HUMAN_HUMAN_STATUE";
        //public const string WORLD_HUMAN_JANITOR = "WORLD_HUMAN_JANITOR";
        //public const string WORLD_HUMAN_JOG_STANDING = "WORLD_HUMAN_JOG_STANDING";
        //public const string WORLD_HUMAN_LEANING = "WORLD_HUMAN_LEANING";
        //public const string WORLD_HUMAN_MAID_CLEAN = "WORLD_HUMAN_MAID_CLEAN";
        //public const string WORLD_HUMAN_MUSCLE_FLEX = "WORLD_HUMAN_MUSCLE_FLEX";
        //public const string WORLD_HUMAN_MUSCLE_FREE_WEIGHTS = "WORLD_HUMAN_MUSCLE_FREE_WEIGHTS";
        //public const string WORLD_HUMAN_MUSICIAN = "WORLD_HUMAN_MUSICIAN";
        //public const string WORLD_HUMAN_PAPARAZZI = "WORLD_HUMAN_PAPARAZZI";
        //public const string WORLD_HUMAN_PARTYING = "WORLD_HUMAN_PARTYING";
        //public const string WORLD_HUMAN_PICNIC = "WORLD_HUMAN_PICNIC";
        //public const string WORLD_HUMAN_PROSTITUTE_HIGH_CLASS = "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS";
        //public const string WORLD_HUMAN_PROSTITUTE_LOW_CLASS = "WORLD_HUMAN_PROSTITUTE_LOW_CLASS";
        //public const string WORLD_HUMAN_PUSH_UPS = "WORLD_HUMAN_PUSH_UPS";
        //public const string WORLD_HUMAN_SEAT_LEDGE = "WORLD_HUMAN_SEAT_LEDGE";
        //public const string WORLD_HUMAN_SEAT_LEDGE_EATING = "WORLD_HUMAN_SEAT_LEDGE_EATING";
        //public const string WORLD_HUMAN_SEAT_STEPS = "WORLD_HUMAN_SEAT_STEPS";
        //public const string WORLD_HUMAN_SEAT_WALL = "WORLD_HUMAN_SEAT_WALL";
        //public const string WORLD_HUMAN_SEAT_WALL_EATING = "WORLD_HUMAN_SEAT_WALL_EATING";
        //public const string WORLD_HUMAN_SEAT_WALL_TABLET = "WORLD_HUMAN_SEAT_WALL_TABLET";
        //public const string WORLD_HUMAN_SECURITY_SHINE_TORCH = "WORLD_HUMAN_SECURITY_SHINE_TORCH";
        //public const string WORLD_HUMAN_SIT_UPS = "WORLD_HUMAN_SIT_UPS";
        //public const string WORLD_HUMAN_SMOKING = "WORLD_HUMAN_SMOKING";
        //public const string WORLD_HUMAN_SMOKING_POT = "WORLD_HUMAN_SMOKING_POT";
        //public const string WORLD_HUMAN_STAND_FIRE = "WORLD_HUMAN_STAND_FIRE";
        //public const string WORLD_HUMAN_STAND_FISHING = "WORLD_HUMAN_STAND_FISHING";
        public const string WORLD_HUMAN_STAND_IMPATIENT = "WORLD_HUMAN_STAND_IMPATIENT";
        public const string WORLD_HUMAN_STAND_IMPATIENT_UPRIGHT = "WORLD_HUMAN_STAND_IMPATIENT_UPRIGHT";
        public const string WORLD_HUMAN_STAND_MOBILE = "WORLD_HUMAN_STAND_MOBILE";
        //public const string WORLD_HUMAN_STAND_MOBILE_UPRIGHT = "WORLD_HUMAN_STAND_MOBILE_UPRIGHT";
        //public const string WORLD_HUMAN_STRIP_WATCH_STAND = "WORLD_HUMAN_STRIP_WATCH_STAND";
        //public const string WORLD_HUMAN_STUPOR = "WORLD_HUMAN_STUPOR";
        //public const string WORLD_HUMAN_SUNBATHE = "WORLD_HUMAN_SUNBATHE";
        //public const string WORLD_HUMAN_SUNBATHE_BACK = "WORLD_HUMAN_SUNBATHE_BACK";
        //public const string WORLD_HUMAN_SUPERHERO = "WORLD_HUMAN_SUPERHERO";
        //public const string WORLD_HUMAN_SWIMMING = "WORLD_HUMAN_SWIMMING";
        //public const string WORLD_HUMAN_TENNIS_PLAYER = "WORLD_HUMAN_TENNIS_PLAYER";
        //public const string WORLD_HUMAN_TOURIST_MAP = "WORLD_HUMAN_TOURIST_MAP";
        //public const string WORLD_HUMAN_TOURIST_MOBILE = "WORLD_HUMAN_TOURIST_MOBILE";
        //public const string WORLD_HUMAN_VEHICLE_MECHANIC = "WORLD_HUMAN_VEHICLE_MECHANIC";
        //public const string WORLD_HUMAN_WELDING = "WORLD_HUMAN_WELDING";
        //public const string WORLD_HUMAN_WINDOW_SHOP_BROWSE = "WORLD_HUMAN_WINDOW_SHOP_BROWSE";
        //public const string WORLD_HUMAN_YOGA = "WORLD_HUMAN_YOGA";
        //public const string WORLD_BOAR_GRAZING = "WORLD_BOAR_GRAZING";
        //public const string WORLD_CAT_SLEEPING_GROUND = "WORLD_CAT_SLEEPING_GROUND";
        //public const string WORLD_CAT_SLEEPING_LEDGE = "WORLD_CAT_SLEEPING_LEDGE";
        //public const string WORLD_COW_GRAZING = "WORLD_COW_GRAZING";
        //public const string WORLD_COYOTE_HOWL = "WORLD_COYOTE_HOWL";
        //public const string WORLD_COYOTE_REST = "WORLD_COYOTE_REST";
        //public const string WORLD_COYOTE_WANDER = "WORLD_COYOTE_WANDER";
        //public const string WORLD_CHICKENHAWK_FEEDING = "WORLD_CHICKENHAWK_FEEDING";
        //public const string WORLD_CHICKENHAWK_STANDING = "WORLD_CHICKENHAWK_STANDING";
        //public const string WORLD_CORMORANT_STANDING = "WORLD_CORMORANT_STANDING";
        //public const string WORLD_CROW_FEEDING = "WORLD_CROW_FEEDING";
        //public const string WORLD_CROW_STANDING = "WORLD_CROW_STANDING";
        //public const string WORLD_DEER_GRAZING = "WORLD_DEER_GRAZING";
        //public const string WORLD_DOG_BARKING_ROTTWEILER = "WORLD_DOG_BARKING_ROTTWEILER";
        //public const string WORLD_DOG_BARKING_RETRIEVER = "WORLD_DOG_BARKING_RETRIEVER";
        //public const string WORLD_DOG_BARKING_SHEPHERD = "WORLD_DOG_BARKING_SHEPHERD";
        //public const string WORLD_DOG_SITTING_ROTTWEILER = "WORLD_DOG_SITTING_ROTTWEILER";
        //public const string WORLD_DOG_SITTING_RETRIEVER = "WORLD_DOG_SITTING_RETRIEVER";
        //public const string WORLD_DOG_SITTING_SHEPHERD = "WORLD_DOG_SITTING_SHEPHERD";
        //public const string WORLD_DOG_BARKING_SMALL = "WORLD_DOG_BARKING_SMALL";
        //public const string WORLD_DOG_SITTING_SMALL = "WORLD_DOG_SITTING_SMALL";
        //public const string WORLD_FISH_IDLE = "WORLD_FISH_IDLE";
        //public const string WORLD_GULL_FEEDING = "WORLD_GULL_FEEDING";
        //public const string WORLD_GULL_STANDING = "WORLD_GULL_STANDING";
        //public const string WORLD_HEN_PECKING = "WORLD_HEN_PECKING";
        //public const string WORLD_HEN_STANDING = "WORLD_HEN_STANDING";
        //public const string WORLD_MOUNTAIN_LION_REST = "WORLD_MOUNTAIN_LION_REST";
        //public const string WORLD_MOUNTAIN_LION_WANDER = "WORLD_MOUNTAIN_LION_WANDER";
        //public const string WORLD_PIG_GRAZING = "WORLD_PIG_GRAZING";
        //public const string WORLD_PIGEON_FEEDING = "WORLD_PIGEON_FEEDING";
        //public const string WORLD_PIGEON_STANDING = "WORLD_PIGEON_STANDING";
        //public const string WORLD_RABBIT_EATING = "WORLD_RABBIT_EATING";
        //public const string WORLD_RATS_EATING = "WORLD_RATS_EATING";
        //public const string WORLD_SHARK_SWIM = "WORLD_SHARK_SWIM";
        //public const string PROP_BIRD_IN_TREE = "PROP_BIRD_IN_TREE";
        //public const string PROP_BIRD_TELEGRAPH_POLE = "PROP_BIRD_TELEGRAPH_POLE";
        //public const string PROP_HUMAN_ATM = "PROP_HUMAN_ATM";
        //public const string PROP_HUMAN_BBQ = "PROP_HUMAN_BBQ";
        //public const string PROP_HUMAN_BUM_BIN = "PROP_HUMAN_BUM_BIN";
        //public const string PROP_HUMAN_BUM_SHOPPING_CART = "PROP_HUMAN_BUM_SHOPPING_CART";
        //public const string PROP_HUMAN_MUSCLE_CHIN_UPS = "PROP_HUMAN_MUSCLE_CHIN_UPS";
        //public const string PROP_HUMAN_MUSCLE_CHIN_UPS_ARMY = "PROP_HUMAN_MUSCLE_CHIN_UPS_ARMY";
        //public const string PROP_HUMAN_MUSCLE_CHIN_UPS_PRISON = "PROP_HUMAN_MUSCLE_CHIN_UPS_PRISON";
        //public const string PROP_HUMAN_PARKING_METER = "PROP_HUMAN_PARKING_METER";
        //public const string PROP_HUMAN_SEAT_ARMCHAIR = "PROP_HUMAN_SEAT_ARMCHAIR";
        //public const string PROP_HUMAN_SEAT_BAR = "PROP_HUMAN_SEAT_BAR";
        //public const string PROP_HUMAN_SEAT_BENCH = "PROP_HUMAN_SEAT_BENCH";
        //public const string PROP_HUMAN_SEAT_BENCH_DRINK = "PROP_HUMAN_SEAT_BENCH_DRINK";
        //public const string PROP_HUMAN_SEAT_BENCH_DRINK_BEER = "PROP_HUMAN_SEAT_BENCH_DRINK_BEER";
        //public const string PROP_HUMAN_SEAT_BENCH_FOOD = "PROP_HUMAN_SEAT_BENCH_FOOD";
        //public const string PROP_HUMAN_SEAT_BUS_STOP_WAIT = "PROP_HUMAN_SEAT_BUS_STOP_WAIT";
        //public const string PROP_HUMAN_SEAT_CHAIR = "PROP_HUMAN_SEAT_CHAIR";
        //public const string PROP_HUMAN_SEAT_CHAIR_DRINK = "PROP_HUMAN_SEAT_CHAIR_DRINK";
        //public const string PROP_HUMAN_SEAT_CHAIR_DRINK_BEER = "PROP_HUMAN_SEAT_CHAIR_DRINK_BEER";
        //public const string PROP_HUMAN_SEAT_CHAIR_FOOD = "PROP_HUMAN_SEAT_CHAIR_FOOD";
        //public const string PROP_HUMAN_SEAT_CHAIR_UPRIGHT = "PROP_HUMAN_SEAT_CHAIR_UPRIGHT";
        //public const string PROP_HUMAN_SEAT_CHAIR_MP_PLAYER = "PROP_HUMAN_SEAT_CHAIR_MP_PLAYER";
        //public const string PROP_HUMAN_SEAT_COMPUTER = "PROP_HUMAN_SEAT_COMPUTER";
        //public const string PROP_HUMAN_SEAT_DECKCHAIR = "PROP_HUMAN_SEAT_DECKCHAIR";
        //public const string PROP_HUMAN_SEAT_DECKCHAIR_DRINK = "PROP_HUMAN_SEAT_DECKCHAIR_DRINK";
        //public const string PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS = "PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS";
        //public const string PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS_PRISON = "PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS_PRISON";
        //public const string PROP_HUMAN_SEAT_SEWING = "PROP_HUMAN_SEAT_SEWING";
        //public const string PROP_HUMAN_SEAT_STRIP_WATCH = "PROP_HUMAN_SEAT_STRIP_WATCH";
        //public const string PROP_HUMAN_SEAT_SUNLOUNGER = "PROP_HUMAN_SEAT_SUNLOUNGER";
        //public const string PROP_HUMAN_STAND_IMPATIENT = "PROP_HUMAN_STAND_IMPATIENT";
        //public const string CODE_HUMAN_COWER = "CODE_HUMAN_COWER";
        //public const string CODE_HUMAN_CROSS_ROAD_WAIT = "CODE_HUMAN_CROSS_ROAD_WAIT";
        //public const string CODE_HUMAN_PARK_CAR = "CODE_HUMAN_PARK_CAR";
        //public const string PROP_HUMAN_MOVIE_BULB = "PROP_HUMAN_MOVIE_BULB";
        //public const string PROP_HUMAN_MOVIE_STUDIO_LIGHT = "PROP_HUMAN_MOVIE_STUDIO_LIGHT";
        //public const string CODE_HUMAN_MEDIC_KNEEL = "CODE_HUMAN_MEDIC_KNEEL";
        //public const string CODE_HUMAN_MEDIC_TEND_TO_DEAD = "CODE_HUMAN_MEDIC_TEND_TO_DEAD";
        public const string CODE_HUMAN_MEDIC_TIME_OF_DEATH = "CODE_HUMAN_MEDIC_TIME_OF_DEATH";
        //public const string CODE_HUMAN_POLICE_CROWD_CONTROL = "CODE_HUMAN_POLICE_CROWD_CONTROL";
        //public const string CODE_HUMAN_POLICE_INVESTIGATE = "CODE_HUMAN_POLICE_INVESTIGATE";
        //public const string CODE_HUMAN_STAND_COWER = "CODE_HUMAN_STAND_COWER";
        //public const string EAR_TO_TEXT = "EAR_TO_TEXT";
        //public const string EAR_TO_TEXT_FAT = "EAR_TO_TEXT_FAT";
        //public const string DRIVE = "DRIVE";
        //public const string WORLD_VEHICLE_POLICE_BIKE = "WORLD_VEHICLE_POLICE_BIKE";
        //public const string WORLD_VEHICLE_POLICE_CAR = "WORLD_VEHICLE_POLICE_CAR";
        //public const string WORLD_VEHICLE_POLICE_NEXT_TO_CAR = "WORLD_VEHICLE_POLICE_NEXT_TO_CAR";
        //public const string WORLD_VEHICLE_DRIVE_SOLO = "WORLD_VEHICLE_DRIVE_SOLO";
        //public const string WORLD_VEHICLE_BIKER = "WORLD_VEHICLE_BIKER";
        //public const string WORLD_VEHICLE_DRIVE_PASSENGERS = "WORLD_VEHICLE_DRIVE_PASSENGERS";
        //public const string WORLD_VEHICLE_SALTON_DIRT_BIKE = "WORLD_VEHICLE_SALTON_DIRT_BIKE";
        //public const string WORLD_VEHICLE_BICYCLE_MOUNTAIN = "WORLD_VEHICLE_BICYCLE_MOUNTAIN";
        //public const string WORLD_VEHICLE_ATTRACTOR = "WORLD_VEHICLE_ATTRACTOR";
        //public const string WORLD_HUMAN_HIKER = "WORLD_HUMAN_HIKER";
        //public const string WORLD_VEHICLE_EMPTY = "WORLD_VEHICLE_EMPTY";
        //public const string WORLD_VEHICLE_BIKE_OFF_ROAD_RACE = "WORLD_VEHICLE_BIKE_OFF_ROAD_RACE";
        //public const string WORLD_VEHICLE_PARK_PERPENDICULAR_NOSE_IN = "WORLD_VEHICLE_PARK_PERPENDICULAR_NOSE_IN";
        //public const string WORLD_VEHICLE_PARK_PARALLEL = "WORLD_VEHICLE_PARK_PARALLEL";
        //public const string WORLD_VEHICLE_CONSTRUCTION_SOLO = "WORLD_VEHICLE_CONSTRUCTION_SOLO";
        //public const string WORLD_VEHICLE_CONSTRUCTION_PASSENGERS = "WORLD_VEHICLE_CONSTRUCTION_PASSENGERS";
        //public const string WORLD_VEHICLE_TRUCK_LOGS = "WORLD_VEHICLE_TRUCK_LOGS";
        //public const string WORLD_HUMAN_MUSICIAN_MALE_GUITAR = "WORLD_HUMAN_MUSICIAN_MALE_GUITAR";
        //public const string WORLD_HUMAN_MUSICIAN_MALE_BONGOS = "WORLD_HUMAN_MUSICIAN_MALE_BONGOS";

        public static void StartInPlace(Ped ped, string scenarioName, bool playEnterAnim, int unkDelay = 0)
        {
            NativeFunction.CallByName<uint>("TASK_START_SCENARIO_IN_PLACE", ped, scenarioName, unkDelay, playEnterAnim);
        }

        public static void StartAtPosition(Ped ped, string scenarioName, Vector3 position, float heading)
        {
            NativeFunction.CallByName<uint>("TASK_START_SCENARIO_AT_POSITION", ped, scenarioName, position.X, position.Y, position.Z, heading, 0, 0, 1);
        }
    }
}
