namespace WildernessCallouts.Types
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;
    //http://pastebin.com/Lrh4v1f7
    internal static class Speech
    {
        public const string APOLOGY_NO_TROUBLE = "APOLOGY_NO_TROUBLE";
        public const string BLOCKED_GENERIC = "BLOCKED_GENERIC";
        public const string BUMP = "BUMP";
        public const string CHAT_RESP = "CHAT_RESP";
        public const string CHAT_STATE = "CHAT_STATE";
        public const string COVER_ME = "COVER_ME";
        public const string COVER_YOU = "COVER_YOU";
        public const string DYING_HELP = "DYING_HELP";
        public const string DYING_MOAN = "DYING_MOAN";
        public const string FALL_BACK = "FALL_BACK";
        public const string GENERIC_BYE = "GENERIC_BYE";
        public const string GENERIC_CURSE_HIGH = "GENERIC_CURSE_HIGH";
        public const string GENERIC_CURSE_MED = "GENERIC_CURSE_MED";
        public const string GENERIC_FRIGHTENED_HIGH = "GENERIC_FRIGHTENED_HIGH";
        public const string GENERIC_FRIGHTENED_MED = "GENERIC_FRIGHTENED_MED";
        public const string GENERIC_FUCK_YOU = "GENERIC_FUCK_YOU";
        public const string GENERIC_HI = "GENERIC_HI";
        public const string GENERIC_HOWS_IT_GOING = "GENERIC_HOWS_IT_GOING";
        public const string GENERIC_INSULT_MED = "GENERIC_INSULT_MED";
        public const string GENERIC_INSULT_HIGH = "GENERIC_INSULT_HIGH";
        public const string GENERIC_SHOCKED_HIGH = "GENERIC_SHOCKED_HIGH";
        public const string GENERIC_SHOCKED_MED = "GENERIC_SHOCKED_MED";
        public const string GENERIC_THANKS = "GENERIC_THANKS";
        public const string GENERIC_YES = "GENERIC_YES";
        public const string GENERIC_WAR_CRY = "GENERIC_WAR_CRY";
        public const string HOOKER_CAR_INCORRECT = "HOOKER_CAR_INCORRECT";
        public const string HOOKER_DECLINE_SERVICE = "HOOKER_DECLINE_SERVICE";
        public const string HOOKER_DECLINED = "HOOKER_DECLINED";
        public const string HOOKER_DECLINED_TREVOR = "HOOKER_DECLINED_TREVOR";
        public const string HOOKER_HAD_ENOUGH = "HOOKER_HAD_ENOUGH";
        public const string HOOKER_LEAVES_ANGRY = "HOOKER_LEAVES_ANGRY";
        public const string HOOKER_OFFER_AGAIN = "HOOKER_OFFER_AGAIN";
        public const string HOOKER_OFFER_SERVICE = "HOOKER_OFFER_SERVICE";
        public const string HOOKER_REQUEST = "HOOKER_REQUEST";
        public const string HOOKER_SECLUDED = "HOOKER_SECLUDED";
        public const string HOOKER_STORY_REVULSION_RESP = "HOOKER_STORY_REVULSION_RESP";
        public const string HOOKER_STORY_SARCASTIC_RESP = "HOOKER_STORY_SARCASTIC_RESP";
        public const string HOOKER_STORY_SYMPATHETIC_RESP = "HOOKER_STORY_SYMPATHETIC_RESP";
        public const string KIFFLOM_GREET = "KIFFLOM_GREET";
        public const string KILLED_ALL = "KILLED_ALL";
        public const string PROVOKE_TRESPASS = "PROVOKE_TRESPASS";
        public const string PURCHASE_ONLINE = "PURCHASE_ONLINE";
        public const string RELOADING = "RELOADING";
        public const string ROLLERCOASTER_CHAT_EXCITED = "ROLLERCOASTER_CHAT_EXCITED";
        public const string ROLLERCOASTER_CHAT_NORMAL = "ROLLERCOASTER_CHAT_NORMAL";
        public const string SEX_CLIMAX = "SEX_CLIMAX";
        public const string SEX_FINISHED = "SEX_FINISHED";
        public const string SEX_GENERIC = "SEX_GENERIC";
        public const string SEX_GENERIC_FEM = "SEX_GENERIC_FEM";
        public const string SEX_ORAL = "SEX_ORAL";
        public const string SEX_ORAL_FEM = "SEX_ORAL_FEM";
        public const string SHOOT = "SHOOT";
        public const string SHOP_BANTER = "SHOP_BANTER";
        public const string SHOP_BANTER_FRANKLIN = "SHOP_BANTER_FRANKLIN";
        public const string SHOP_BANTER_TREVOR = "SHOP_BANTER_TREVOR";
        public const string SHOP_BROWSE = "SHOP_BROWSE";
        public const string SHOP_BROWSE_ARMOUR = "SHOP_BROWSE_ARMOUR";
        public const string SHOP_BROWSE_BIG = "SHOP_BROWSE_BIG";
        public const string SHOP_BROWSE_FRANKLIN = "SHOP_BROWSE_FRANKLIN";
        public const string SHOP_BROWSE_GUN = "SHOP_BROWSE_GUN";
        public const string SHOP_BROWSE_MELEE = "SHOP_BROWSE_MELEE";
        public const string SHOP_BROWSE_TATTOO_MENU = "SHOP_BROWSE_TATTOO_MENU";
        public const string SHOP_BROWSE_THROWN = "SHOP_BROWSE_THROWN";
        public const string SHOP_BROWSE_TREVOR = "SHOP_BROWSE_TREVOR";
        public const string SHOP_CUTTING_HAIR = "SHOP_CUTTING_HAIR";
        public const string SHOP_GIVE_FOR_FREE = "SHOP_GIVE_FOR_FREE";
        public const string SHOP_GOODBYE = "SHOP_GOODBYE";
        public const string SHOP_GREET = "SHOP_GREET";
        public const string SHOP_GREET_FRANKLIN = "SHOP_GREET_FRANKLIN";
        public const string SHOP_GREET_MICHAEL = "SHOP_GREET_MICHAEL";
        public const string SHOP_GREET_SPECIAL = "SHOP_GREET_SPECIAL";
        public const string SHOP_GREET_TREVOR = "SHOP_GREET_TREVOR";
        public const string SHOP_GREET_UNUSUAL = "SHOP_GREET_UNUSUAL";
        public const string SHOP_HAIR_WHAT_WANT = "SHOP_HAIR_WHAT_WANT";
        public const string SHOP_NICE_VEHICLE = "SHOP_NICE_VEHICLE";
        public const string SHOP_NO_COPS = "SHOP_NO_COPS";
        public const string SHOP_NO_MESSING = "SHOP_NO_MESSING";
        public const string SHOP_NO_WEAPON = "SHOP_NO_WEAPON";
        public const string SHOP_OUT_OF_STOCK = "SHOP_OUT_OF_STOCK";
        public const string SHOP_REMOVE_VEHICLE = "SHOP_REMOVE_VEHICLE";
        public const string SHOP_SELL = "SHOP_SELL";
        public const string SHOP_SELL_ARMOUR = "SHOP_SELL_ARMOUR";
        public const string SHOP_SELL_BRAKES = "SHOP_SELL_BRAKES";
        public const string SHOP_SELL_BULLETPROOF_TYRES = "SHOP_SELL_BULLETPROOF_TYRES";
        public const string SHOP_SELL_COSMETICS = "SHOP_SELL_COSMETICS";
        public const string SHOP_SELL_ENGINE_UPGRADE = "SHOP_SELL_ENGINE_UPGRADE";
        public const string SHOP_SELL_EXHAUST = "SHOP_SELL_EXHAUST";
        public const string SHOP_SELL_HORN = "SHOP_SELL_HORN";
        public const string SHOP_SELL_REPAIR = "SHOP_SELL_REPAIR";
        public const string SHOP_SELL_SUSPENSION = "SHOP_SELL_SUSPENSION";
        public const string SHOP_SELL_TRANS_UPGRADE = "SHOP_SELL_TRANS_UPGRADE";
        public const string SHOP_SELL_TURBO = "SHOP_SELL_TURBO";
        public const string SHOP_SHOOTING = "SHOP_SHOOTING";
        public const string SHOP_SPECIAL_DISCOUNT = "SHOP_SPECIAL_DISCOUNT";
        public const string SHOP_TATTOO_APPLIED = "SHOP_TATTOO_APPLIED";
        public const string SHOP_TRY_ON_ITEM = "SHOP_TRY_ON_ITEM";
        public const string SHOUT_THREATEN_GANG = "SHOUT_THREATEN_GANG";
        public const string SHOUT_THREATEN_PED = "SHOUT_THREATEN_PED";
        public const string SOLICIT_FRANKLIN = "SOLICIT_FRANKLIN";
        public const string SOLICIT_FRANKLIN_RETURN = "SOLICIT_FRANKLIN_RETURN";
        public const string SOLICIT_MICHAEL = "SOLICIT_MICHAEL";
        public const string SOLICIT_MICHAEL_RETURN = "SOLICIT_MICHAEL_RETURN";
        public const string SOLICIT_TREVOR = "SOLICIT_TREVOR";
        public const string SOLICIT_TREVOR_RETURN = "SOLICIT_TREVOR_RETURN";
        public const string STAY_DOWN = "STAY_DOWN";
        public const string TAKE_COVER = "TAKE_COVER";
        public const string CAR_HIT_PED = "CAR_HIT_PED";
        public const string ARRESTED = "ARRESTED";
        public const string DODGE = "DODGE";
        public const string GUN_COOL = "GUN_COOL";
        public const string DRAW_GUN = "DRAW_GUN";
        public const string FIGHT = "FIGHT";
        public const string FIGHT_RUN = "FIGHT_RUN";
        public const string JACKED_CAR = "JACKED_CAR";
        public const string JACKED_GENERIC = "JACKED_GENERIC";
        public const string JACKING_BIKE = "JACKING_BIKE";
        public const string JACKING_CAR_MALE = "JACKING_CAR_MALE";
        public const string JACKING_GENERIC = "JACKING_GENERIC";
        public const string JACKING_ORDER = "JACKING_ORDER";
        public const string KNOCK_OVER_PED = "KNOCK_OVER_PED";
        public const string MELEE_KNOCK_DOWN = "MELEE_KNOCK_DOWN";
        public const string START_CAR_PANIC = "START_CAR_PANIC";
        public const string BLOCKED_IN_PURSUIT = "BLOCKED_IN_PURSUIT";
        public const string TRAPPED = "TRAPPED";
        public const string SURROUNDED = "SURROUNDED";
        public const string PINNED_DOWN = "PINNED_DOWN";
        public const string DUCK = "DUCK";
        public const string ARREST_PLAYER = "ARREST_PLAYER";
        public const string OFFICER_DOWN = "OFFICER_DOWN";
        public const string FIRE_IS_OUT = "FIRE_IS_OUT";
        public const string SCREAM = "SCREAM";
        public const string GROWL = "GROWL";
        public const string IDLE = "IDLE";
        public const string RUN_OVER_PLAYER = "RUN_OVER_PLAYER";
        public const string BUM_SPARE_CHANGE = "BUM_SPARE_CHANGE";
        public const string CHAT_ACROSS_STREET_STATE = "CHAT_ACROSS_STREET_STATE";
        public const string CHAT_ACROSS_STREET_RESP = "CHAT_ACROSS_STREET_RESP";
        public const string FRIEND_FOLLOWED_BY_PLAYER = "FRIEND_FOLLOWED_BY_PLAYER";
        public const string GREET_ACROSS_STREET = "GREET_ACROSS_STREET";
        public const string INSULT_PED_BUM = "INSULT_PED_BUM";
        public const string INSULT_PED_COP = "INSULT_PED_COP";
        public const string INSULT_DEAD_PED = "INSULT_DEAD_PED";
        public const string INSULT_PED_FAT = "INSULT_PED_FAT";
        public const string INSULT_PED_GANG = "INSULT_PED_GANG";
        public const string INSULT_PED_HIPSTER = "INSULT_PED_HIPSTER";
        public const string INSULT_PED_JUNKIE = "INSULT_PED_JUNKIE";
        public const string INSULT_PED_OLD = "INSULT_PED_OLD";
        public const string INSULT_PED_TOUGH = "INSULT_PED_TOUGH";
        public const string SHOUT_PERV_AT_WOMAN_PERV = "SHOUT_PERV_AT_WOMAN_PERV";
        public const string JEERING_RESP = "JEERING_RESP";
        public const string HOWS_IT_GOING_FEMALE = "HOWS_IT_GOING_FEMALE";
        public const string PED_RANT = "PED_RANT";
        public const string HOWS_IT_GOING_MALE = "HOWS_IT_GOING_MALE";
        public const string SEE_FRANKLIN = "SEE_FRANKLIN";
        public const string SEE_LAMAR = "SEE_LAMAR";
        public const string SEE_WEIRDO = "SEE_WEIRDO";
        public const string SHOUT_INSULT = "SHOUT_INSULT";
        public const string GENERIC_WHATEVER = "GENERIC_WHATEVER";
        public const string SHOUT_INSULT_HIPSTER = "SHOUT_INSULT_HIPSTER";
        public const string SHOUT_THREATEN_COP = "SHOUT_THREATEN_COP";
        public const string SHOUT_WEIRDO = "SHOUT_WEIRDO";
        public const string GENERIC_UNFIT = "GENERIC_UNFIT";

        public static List<string> GetAllSpeeches()
        {
            List<string> list = new List<string>();
            foreach (var item in typeof(Speech).GetFields(BindingFlags.Public | BindingFlags.Static | BindingFlags.FlattenHierarchy).Where(fi => fi.IsLiteral && !fi.IsInitOnly))
            {
                list.Add((string)item.GetRawConstantValue());
            }
            return list;
        }
    }
}
